name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-4x
  - conda-forge
dependencies:
  - xeus-cpp
  - symengine
  - xtensor-blas
  - xsimd
  - xwidgets
  - xcanvas
  - pip:
      - ipycanvas==0.11
